Repository OpenLightingProject/ola, pull requests merged in 2023-02, with the labels that each got.

#1813 New WebUI: Update angular and angular-route and add workaround to be compatible
  javascript/new-src/bower.json
  javascript/new-src/package.json
  javascript/new-src/src/app.js
  olad/www/new/css/style.min.css
  olad/www/new/js/app.min.js
  olad/www/new/js/app.min.js.map
  olad/www/new/libs/angular-route/js/angular-route.min.js
  olad/www/new/libs/angular/js/angular.min.js
  olad/www/new/libs/jquery/js/jquery.min.js
Labels: bug, Component-UI, Language-JS

#1761 Fix vast majority of outstanding Python 3 issues
  .codespellignorelines
  .gitignore
  NEWS
  configure.ac
  python/ola/Makefile.mk
  python/ola/PidStore.py
  python/ola/PidStoreTest.py
  python/ola/StringUtils.py
  python/ola/StringUtilsTest.py
  tools/rdm/ExpectedResultsTest.py
  tools/rdm/Makefile.mk
  tools/rdm/ResponderTest.py
  tools/rdm/ResponderTestTest.py
  tools/rdm/TestDefinitions.py
  tools/rdm/TestHelpers.py
  tools/rdm/TestHelpersTest.py
  tools/rdm/TestLogger.py
  tools/rdm/TestMixins.py
  tools/rdm/TestRunner.py
  tools/rdm/TestRunnerTest.py
  tools/rdm/TestStateTest.py
  tools/rdm/rdm_responder_test.py
  tools/rdm/rdm_test_server.py
Labels: Maintainability

#1822 Master resync
  .codespellignorelines
  .codespellignorewords
  .github/problem-matcher-lint-spellintian.json
  .github/workflows/lint.yaml
  .gitignore
  Makefile.am
  NEWS
  common/rdm/testdata/test_pids.proto
  configure.ac
  python/ola/Makefile.mk
  python/ola/PidStore.py
  python/ola/PidStoreTest.py
  python/ola/StringUtils.py
  python/ola/StringUtilsTest.py
  scripts/spelling.sh
  tools/rdm/ExpectedResultsTest.py
  tools/rdm/Makefile.mk
  tools/rdm/ResponderTest.py
  tools/rdm/ResponderTestTest.py
  tools/rdm/TestDefinitions.py
  tools/rdm/TestHelpers.py
  tools/rdm/TestHelpersTest.py
  tools/rdm/TestLogger.py
  tools/rdm/TestMixins.py
  tools/rdm/TestRunner.py
  tools/rdm/TestRunnerTest.py
  tools/rdm/TestStateTest.py
  tools/rdm/rdm_responder_test.py
  tools/rdm/rdm_test_server.py
Labels: retrospective-review-required
